export const INSURANCE_PARTNERS = [
  { name: 'BUPA', domain: 'bupa.com.sa' },
  { name: 'TAWUNIYA', domain: 'tawuniya.com.sa' },
  { name: 'MEDGULF', domain: 'medgulf.com.sa' },
  { name: 'GULF UNION', domain: 'gulfunion-saudi.com' },
  { name: 'GIG', domain: 'gig.sa' },
  { name: 'MALATH', domain: 'malath.com.sa' },
  { name: 'ALRAJHI', domain: 'alrajhitakaful.com' },
  { name: 'SAICO', domain: 'saico.com.sa' },
  { name: 'WALA', domain: 'walaa.com' },
  { name: 'ARABIA', domain: 'arabia-sa.com' },
  { name: 'ALLIED', domain: 'allied-insurance.com' },
  { name: 'AL JAZEERA', domain: 'aljaziratakaful.com.sa' },
  { name: 'AL ETIHAD', domain: 'tuic-sa.com' },
  { name: 'ARABIAN SHIELD', domain: 'der3.com' },
  { name: 'AL SAGAR', domain: 'alsagr.com' },
  { name: 'BURUJ', domain: 'burujinsurance.com' },
  { name: 'CIGNA', domain: 'cigna.com' },
  { name: 'MUTAKAMELA', domain: '' },
  { name: 'AMANA', domain: 'amana-coop.com.sa' },
  { name: 'ORIENT', domain: 'orientonline.com.sa' },
  { name: 'SALAMA', domain: 'salama.com.sa' },
  { name: 'SAUDI ENAYA', domain: 'saudi-enaya.com' },
  { name: 'ORIENT INSURANCE', domain: 'orientonline.com.sa' },
  { name: 'GULF GENERAL', domain: 'ggi-sa.com' },
  { name: 'TCS (TOTAL CARE SAUDI)', domain: 'totalcaresaudi.com' },
  { name: 'SNC (SAUDI NEXTCARE)', domain: 'nextcarehealth.com' },
  { name: 'GLOBEMED', domain: 'globemedsaudi.com' },
];
