export const INSURANCE_PARTNERS = [
  { name: 'BUPA', image: 'bupa.png' },
  { name: 'TAWUNIYA', image: 'tawuniya.jpg' },
  { name: 'MEDGULF', image: 'medgulf.jpg' },
  { name: 'GULF UNION', image: 'gulfunion.png' },
  { name: 'GIG', image: 'gig.png' },
  { name: 'MALATH', image: 'malath.png' },
  { name: 'ALRAJHI', image: 'al-rajhi.webp' },
  { name: 'SAICO', image: 'saico.png' },
  { name: 'WALA', image: 'wala.jpg' },
  { name: 'ARABIA', image: 'arabia.jpg' },
  { name: 'ALLIED', image: 'allied.jpg' },
  { name: 'AL JAZEERA', image: 'al-jazeera.jpg' },
  { name: 'AL ETIHAD', image: 'al-etihad.png' },
  { name: 'ARABIAN SHIELD', image: 'arabian-shield.jpg' },
  { name: 'AL SAGAR', image: 'al-sagar.jpg' },
  { name: 'BURUJ', image: 'burj.png' },
  { name: 'CIGNA', image: 'cigna.png' },
  { name: 'MUTAKAMELA', image: 'mutakamela.jpg' },
  { name: 'AMANA', image: 'amana.png' },
  { name: 'ORIENT', image: 'orintal.png' },
  { name: 'SALAMA', image: 'salama.png' },
  { name: 'SAUDI ENAYA', image: 'saudi-enaya.png' },
  { name: 'GULF GENERAL', image: 'gulf-genral.png' },
  { name: 'TCS (TOTAL CARE SAUDI)', image: 'tcs.png' },
  { name: 'SNC (SAUDI NEXTCARE)', image: 'nextcare.png' },
  { name: 'GLOBEMED', image: 'globemed.jpg' },
];
